###############
# STEPS
#steps: ["coverage", "binning", "mdmcleaner", "checkm", "gtdbtk", "abundance"]       #TODO: metachip, spades
steps: "coverage"

##############
# INPUT
# working_directory
work_dir: "/scratch/users/kdixit/gitrepos/Metabinner"

# Directory where fastq files are
read_dir: "/mnt/lscratch/users/kdixit/rawdata/stool"

# Directory where the assemblies are stored
assembly_dir: "/mnt/lscratch/users/kdixit/rawdata/stool_assemblies"

# Directory to save the output to
results_dir: "/mnt/lscratch/users/kdixit/metabinner_results/stool_results"

# Directory with databases
db_dir: "/scratch/users/gmichoud/DB"

# Directory with conda envs
env_dir: "/scratch/users/kdixit/gitrepos/Metabinner/envs"

##############
# TOOLS and parameters
# Number of cpus or threads to use
threads: 28

filter_length:
    threads: 4
    
mdmcleaner:
    threads: 7

mapping:
    threads: 7

metabat2:
    threads: 14

concoct:
    threads: 14

metabinner:
    length: 2000
    threads: 14

dasTool:
    threads: 14

checkM:
    threads: 14

dRep:
    threads: 28
    comp: 70
    cont: 10

gtdbtk:
    threads: 14
    path: "/scratch/users/gmichoud/DB/release207_v2"
